### ISSUE TITLE
Migrations are not compatible with Django < 1.7

### ISSUE THREAD

**Issue by Perados** [evonove/django-oauth-toolkit#290]
Maybe I am missing something, but this line is breaking Django < 1.7 even if the changelog says it supports it:

from django.db import models, migrations 
That is in oauth2_provider/migrations/0001_initial.py

Now, I know there is a south_migrations folder, but when I run ./manage.py migrate, I still get the famous error: ImportError: cannot import name migrations

Am I doing something wrong? Is there a way to run only the south_migrations and no other ones?

Thank you!

P.S.: This guy had the same problem apparently: https://groups.google.com/forum/#!topic/django-oauth-toolkit/5XIKPFvXNBE

EDIT: I found what I was missing. Just add the following lines to your settings.py and it will work with Django 1.6:

```python
SOUTH_MIGRATION_MODULES = {
    'oauth2_provider': 'oauth2_provider.south_migrations',
}
```

**Comment by JannKleen** [comment]
Are you using South >= 1.0.0 ?
Because South should be looking into the folder ```south_migrations``` on its own (s. https://south.readthedocs.org/en/latest/releasenotes/1.0.html#library-migration-path)

**Comment by Perados** [comment]
We use South 0.8.4

**Comment by synasius** [comment]
@Perados Did you manage to solve by upgrading south 1.0.0??

**Comment by Perados** [comment]
@synasius no, I couldn't do that on production, but I fixed it by adding the following lines to my settings.py on Django 1.6:

SOUTH_MIGRATION_MODULES = {
'oauth2_provider': 'oauth2_provider.south_migrations',
}

Hope it helps!

**Comment by synasius** [comment]
@Perados Ok! I'll close the issue since both upgrading to South 1.0 or using `SOUTH_MIGRATION_MODULES` setting are valid solutions.
