### ISSUE TITLE
OAUTH2_PROVIDER_APPLICATION_MODEL default not loaded into settings

### ISSUE THREAD

**Issue by yarbelk** [evonove/django-oauth-toolkit#240]
I have a migration that depends on the application model being there - but since I'm not overriding the applicaiton model, I don't see the OAUTH2_PROVIDER_APPLICATION_MODEL in the settings.

Using django-configurations as well.

**Comment by jkkjonah** [comment]
Hi yarbelk, did you ever find a solution to this issue? We're experiencing the same thing after migrating from django 1.5 to 1.7

**Comment by jdp** [comment]
Seeing this in Django 1.9 when running `makemigrations`. Not trying to use a custom model or anything, but one of my models has a foreign key to `oauth2_provider.Application`.

> AttributeError: 'Settings' object has no attribute 'OAUTH2_PROVIDER_APPLICATION_MODEL'

Adding the setting fixes it, but it seems heavy-handed to fix it like that.

**Comment by b35li** [comment]
@jdp How do you fix the settings, I get the error right now , but no idea how to fix it.

**Comment by jdp** [comment]
@b35li copy the setting into your settings.py, like this:

``` python
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
```

**Comment by jleclanche** [comment]
Closing as these versions of Django are no longer supported.

**Comment by dv321** [comment]
@jleclanche  this is still happening with django 1.10.7, can you point me in the direction of what would need to be done to get a pr in for this?

**Comment by apiraino** [comment]
Hi, as @jleclanche said this undocumented behaviour looks like is still there.

I'm running Django 1.11.5 and I think it's a problem of circular imports that I still didn't figure out. The issue is triggered by a deadly combo of these params I'm using in my tests:
`-n`: I've installed [Django Test Without Migrations](https://github.com/henriquebastos/django-test-without-migrations)
`-v 2`: with verbose level set to 1 or 0, the issue does not show up.

Example of complete cmd line I'm using:
`$ DJANGO_SETTINGS_MODULE=myprj.settings.test python manage.py test --noinput -n myprj.module.tests.test_class -v 2`

My workaround is to set in my projects settings the two following constants:
```
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'                                                                         
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'                                                                          
```

**Comment by lcary** [comment]
More recently, requires:
```
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth2_provider.RefreshToken'
```
Pasting in case others encounter this open issue as I did.

**Comment by jcampbell05** [comment]
Still happening in Django 2.1

**Comment by pythonwood** [comment]
happen in django2.2 too

**Comment by KhashayarMirMS** [comment]
And happening in Django 3

**Comment by jamilnoyda** [comment]
django 2.2
python 3.7
i was having same the issue, i delete virtualenv folder re-install whole thing again. It worked!

**Comment by PinkFLoyd92** [comment]
I am having this exact problem... Any solution?

**Comment by okke-formsma** [comment]
@PinkFLoyd92 https://github.com/jazzband/django-oauth-toolkit/issues/240#issuecomment-403928239

**Comment by squeral** [comment]
Version 1.5 also requires setting `OAUTH2_PROVIDER_ID_TOKEN_MODEL`.

https://github.com/jazzband/django-oauth-toolkit/blob/9d2aac2480b2a1875eb52612661992f73606bade/tests/settings.py#L137-L140

**Comment by allen-munsch** [comment]
@Icary's answer appears to work on django3.2, when adding a foreignkey of Application

```
# settings.py

OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'
OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth2_provider.RefreshToken'
OAUTH2_PROVIDER_ID_TOKEN_MODEL = "oauth2_provider.IDToken" 

# on a model
    oauth_apps = models.ForeignKey('oauth2_provider.Application', on_delete=models.CASCADE, null=True, blank=True)
```

**Comment by kittu603** [comment]
> More recently, requires:
> 
> ```
> OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL = 'oauth2_provider.AccessToken'
> OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
> OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL = 'oauth2_provider.RefreshToken'
> ```
> 
> Pasting in case others encounter this open issue as I did.

Working!!!! Thanks

**Comment by Clay0126** [comment]
Django：2.2.24
Maybe you can try this.

```python
OAUTH2_PROVIDER_APPLICATION_MODEL="oauth2_provider.Application"
OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL="oauth2_provider.AccessToken"
OAUTH2_PROVIDER_ID_TOKEN_MODEL="oauth2_provider.IDToken"
OAUTH2_PROVIDER_GRANT_MODEL="oauth2_provider.Grant"
OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL="oauth2_provider.RefreshToken"
```

**Comment by AhmedSam3r** [comment]
I had the same issue in django 2.2.7.
It's solved by adding the following keys & values inside oauth2_provider OAUTH2_PROVIDER (in my case I added in settings.py file):
```
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_MODEL': 'oauth2_provider.AccessToken',
    'APPLICATION_MODEL': 'oauth2_provider.Application',
    'REFRESH_TOKEN_MODEL': 'oauth2_provider.RefreshToken',
}

```

**Comment by AhmedSam3r** [comment]
> Django：2.2.24 Maybe you can try this.
> 
> ```python
> OAUTH2_PROVIDER_APPLICATION_MODEL="oauth2_provider.Application"
> OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL="oauth2_provider.AccessToken"
> OAUTH2_PROVIDER_ID_TOKEN_MODEL="oauth2_provider.IDToken"
> OAUTH2_PROVIDER_GRANT_MODEL="oauth2_provider.Grant"
> OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL="oauth2_provider.RefreshToken"
> ```

This one fixes the issue in django 2.2.7 too
